#!/bin/bash

# unmount and de-chroot drives

#drive=$1
name=$1

if [[ $name == '' ]]
then
	echo "chu--the de-chroot script--"
	echo "USAGE: chu [name (of mount point)]"
	exit 1
fi
while true; do
	read -p "Do you want to unmount and de-chroot mount point '/mnt/$name'? [y/n]: " yn
	case $yn in
		[Yy]*) echo "Proceeding to unmount drive"; break ;;
		[Nn]*) echo "Aborted"; exit 1 ;;
	esac
done

echo "unmounting drives..."
sudo umount -l /mnt/$name/dev /mnt/$name/sys
sudo umount /mnt/$name/proc # /mnt/gentoo/boot
sudo umount -l /mnt/$name
#sudo umount /mnt/gentoo
echo "done"
